[package]
name = "mud-client"
version = "0.2.0"
edition = "2021"

[dependencies]
deku = "0.14.1"
mud-opts = { version = "0.2.0", path = "../opts" }
mud-packet = { version = "0.2.0", path = "../packet" }
tokio = { version = "1.22.0", features = ["full"] }
tracing = "0.1.37"
